services:
  postgres:
    container_name: postgres-sql
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Firas123@
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: houri_phone_db
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - spring-demo
    restart: unless-stopped
  houri-phone-api:
    container_name: houri-phone-api
    image: firas709/houri-phone-api:1.0.0
    environment:
      EMAIL_HOST_NAME: ${EMAIL_HOST_NAME}
      EMAIL_USER_NAME: ${EMAIL_USER_NAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
    ports:
      - "8088:8088"
    volumes:
      - bsn-api-storage:/app/uploads
    networks:
      - spring-demo
    depends_on:
      - postgres

  houri-phone-ui:
    container_name: bsn-ui
    image: firas709/houri-phone-ui:1.0.0
    ports:
      - "8080:80"
    networks:
      - spring-demo
    depends_on:
      - houri-phone-api
networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
  bsn-api-storage:
    driver: local

